language: cpp
dist: xenial
sudo: required

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

matrix:
  include:
    # Debug GL
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Debug ENGINE=GL
    # Release GL
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Release ENGINE=GL
    # Clang Debug GL
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - lld-7
            - llvm-7
            - llvm-7-dev
            - llvm-7-runtime
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" BUILD_TYPE=Debug ENGINE=GL
        - EXTRA_FLAGS="-stdlib=libc++"
    # Clang Release GL
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - lld-7
            - llvm-7
            - llvm-7-dev
            - llvm-7-runtime
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" BUILD_TYPE=Release ENGINE=GL
        - EXTRA_FLAGS="-stdlib=libc++"
    # Clang Thread sanitizer
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - lld-7
            - llvm-7
            - llvm-7-dev
            - llvm-7-runtime
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" BUILD_TYPE=Debug ENGINE=GL
        - EXTRA_FLAGS="-stdlib=libc++ -fsanitize=thread"
    # Clang Adress sanitizer
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - lld-7
            - llvm-7
            - llvm-7-dev
            - llvm-7-runtime
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" BUILD_TYPE=Debug ENGINE=GL
        - EXTRA_FLAGS="-stdlib=libc++ -fsanitize=address"
    # Debug Vk
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Debug ENGINE=Vk
    # Release Vk
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8" BUILD_TYPE=Release ENGINE=Vk
    # Clang Debug Vk
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - lld-7
            - llvm-7
            - llvm-7-dev
            - llvm-7-runtime
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" BUILD_TYPE=Debug ENGINE=Vk
        - EXTRA_FLAGS="-stdlib=libc++"
    # Clang Release Vk
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - lld-7
            - llvm-7
            - llvm-7-dev
            - llvm-7-runtime
            - libgl1-mesa-dev
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7" BUILD_TYPE=Release ENGINE=Vk
        - EXTRA_FLAGS="-stdlib=libc++"
        
before_install:
    - eval "${MATRIX_EVAL}"
    - wget http://www.cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.sh
    - sudo sh cmake-3.13.0-Linux-x86_64.sh --skip-license --prefix=/usr
    - export PATH=/usr/bin:$PATH
# Build steps

script:
- gcc -v && g++ -v && cmake --version
- clang --version
- cd libs/glew/build
- cmake ../build/cmake/.
- sudo make -j2 && sudo make install
- cd ../../../
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" -DTEMPEST_BUILD_ALL=ON -DENGINE="${ENGINE}"
- make -j2
- ./exe/core_test
- if [ "${BUILD_TYPE}" == "Release" ]; then
    ./exe/queue_test;
  fi
