# version format
version: 0.0.1.{build}
 
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  GENERATOR: "Visual Studio 15 2017 Win64"

  matrix:
  - ENGINE: "GL"
  - ENGINE: "Vk"
    VULKAN_SDK: "c:\VulkanSDK\1.0.51.0"

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive
    - curl --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.101.0/windows/VulkanSDK-1.0.101.0-Installer.exe .\VulkanSDK.exe /S

before_build:
    - cmd: echo %GENERATOR%
    - cmd: cmake -G"%GENERATOR%" . -DTEMPEST_BUILD_ALL=ON -DENGINE=%ENGINE%
    - sh: cmake . 

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
  
test_script:
  - copy %APPVEYOR_BUILD_FOLDER%\libs\glew\bin\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\exe\%CONFIGURATION%\
  - '%APPVEYOR_BUILD_FOLDER%\exe\%CONFIGURATION%\core_test.exe'
  - IF "%configuration%"=="Release" ("%APPVEYOR_BUILD_FOLDER%\exe\%CONFIGURATION%\queue_test.exe")
  