# version format
version: 0.0.1.{build}
 
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019 -A x64"
      ENGINE: "GL"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"
      ENGINE: "GL"

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive
    - IF "%ENGINE%"=="Vk" (curl --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.82.1/windows/VulkanSDK-1.1.82.1-Installer.exe)
    - IF "%ENGINE%"=="Vk" (VulkanSDK.exe /S)

before_build:
    - cmd: echo %GENERATOR%
    - cmd: cmake -G"%GENERATOR%" . -DTEMPEST_BUILD_ALL=ON -DENGINE=%ENGINE%
    - sh: cmake . 

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
  
test_script:
  - copy %APPVEYOR_BUILD_FOLDER%\libs\glew\bin\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\exe\%CONFIGURATION%\
  - '%APPVEYOR_BUILD_FOLDER%\exe\%CONFIGURATION%\core_test.exe'
  - IF "%configuration%"=="Release" ("%APPVEYOR_BUILD_FOLDER%\exe\%CONFIGURATION%\queue_test.exe")
  