name: clang-engine-tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        engine: [Vk, GL]
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
      with:
        submodules: true
    - name: install vulkan
      if: ${{ matrix.engine == 'Vk' }}
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -;
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.148-bionic.list http://packages.lunarg.com/vulkan/1.2.148/lunarg-vulkan-1.2.148-bionic.list;
        sudo apt update;
        sudo apt install lunarg-vulkan-sdk;
    - name: config CMake
      env:
        CC: clang-11
        CXX: clang++-11
        BUILD_TYPE: ${{ matrix.build_type }}
        ENGINE: ${{ matrix.engine }}
      run: | 
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" -DTEMPEST_BUILD_ALL=ON -DENGINE="$ENGINE"