name: gcc-engine-tests
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        engine: [Vk, GL]
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install
      run: sudo apt-get install -y libgl1-mesa-dev libxinerama-dev libxcursor-dev xorg-dev
    - name: build GLEW
      if: ${{ matrix.engine == 'GL'}}
      run: |
        cd libs/glew/build;
        cmake ../build/cmake/.;
        sudo make -j2 && sudo make install;
        cd ../../../;
    - name: config CMake
      env:
        CC: gcc-10
        CXX: g++-10
        BUILD_TYPE: ${{ matrix.build_type }}
        ENGINE: ${{ matrix.engine }}
      run: | 
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${EXTRA_FLAGS}" -DTEMPEST_BUILD_ALL=ON -DENGINE="$ENGINE"
     - name: build
       run: make -j2
     - name: run tests
       run: ./exe/core_test